14Sept2019SirTask/Models/CountryStateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _14Sept2019SirTask.Models
{
    public class CountryStateModel
    {
        public int countryid { get; set; }
        public int stateid { get; set; }
    }
}

14Sept2019SirTask/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14Sept2019SirTask.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_State> tbl_State { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
    }
}

14Sept2019SirTask/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\hp\Desktop\14Sept2019SirTask\14Sept2019SirTask\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

14Sept2019SirTask/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

14Sept2019SirTask/Models/tbl_City.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14Sept2019SirTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_City
    {
        public int cityid { get; set; }
        public string cityname { get; set; }
        public Nullable<int> FKstateid { get; set; }
    
        public virtual tbl_State tbl_State { get; set; }
    }
}

14Sept2019SirTask/Models/tbl_Country.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14Sept2019SirTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Country()
        {
            this.tbl_State = new HashSet<tbl_State>();
        }
    
        public int countryid { get; set; }
        public string countryname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_State> tbl_State { get; set; }
    }
}

14Sept2019SirTask/Models/tbl_State.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14Sept2019SirTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_State()
        {
            this.tbl_City = new HashSet<tbl_City>();
        }
    
        public int stateid { get; set; }
        public string statename { get; set; }
        public Nullable<int> FKcountryid { get; set; }
    
        public virtual tbl_Country tbl_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_City> tbl_City { get; set; }
    }
}

14Sept2019SirTask/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _14Sept2019SirTask.Models;

namespace _14Sept2019SirTask.Controllers
{
    public class LocationController : Controller
    {
        Database1Entities db = new Database1Entities();

        // GET: Location
        public ActionResult Index()
        {
            ViewBag.countryname = new SelectList(db.tbl_Country.ToList(), "countryid", "countryname");
            ViewBag.statename = new List<SelectListItem>(){
                new SelectListItem(){ Text = "", Value="Select State"}
            }; ViewBag.cityname = new List<SelectListItem>() {
                new SelectListItem(){Text="", Value="Select City"}
            };
            return View();
        }


        public JsonResult GetStatesByCountryId(int id)
        {
            return Json(db.tbl_State.Where(a => a.FKcountryid == id).Select(b => new { b.statename, b.stateid }).ToList(),JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCitiesByStateId(int id)
        {
            return Json(db.tbl_City.Where(a => a.FKstateid == id).Select(b => new { b.cityname, b.cityid }).ToList(), JsonRequestBehavior.AllowGet);
        }

    }
}

14Sept2019SirTask/Views/Location/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm())
{
    <td colspan="3">
        <tr>
            <td>Select Country: </td>
        </tr>
        <tr>
            <td>Select State: </td>
        </tr>
        <tr>
            <td>Select City: </td>
        </tr>
    </td>

    <table class="table table-responsive">
        <tr>
            <td>
                @Html.DropDownList("countryname", null, "Select Country", htmlAttributes: new { @class = "form-control" })
            </td>
            <td>
                @Html.DropDownList("statename", null, "Select State", htmlAttributes: new { @class = "form-control" })
            </td>
            <td>
                @Html.DropDownList("cityname", null, "Select City", htmlAttributes: new { @class = "form-control" })
            </td>
        </tr>
    </table>
}

<script>
    $(document).ready(function () {
        $("#countryname").change(function () {
            alert($(this).val());

            var stateurl = "@Url.Action("GetStatesByCountryId","Location")/" + $(this).val();

            $.getJSON(stateurl, null, function (data) {

                var htmlstate="<option>Select State State</option>"

                $.each(data, function (i, v) {
                    htmlstate += `<option value="${v.stateid}">${v.statename}</option>`;
                });

                $("#statename").html(htmlstate);
            });
        });


        $("#statename").change(function () {
            //alert($(this).val());

            var cityurl = "@Url.Action("GetCitiesByStateId","Location")/" + $(this).val();

            $.getJSON(cityurl, null, function (data) {

                var htmlcity="<option>Select City</option>"

                $.each(data, function (i, v) {
                    htmlcity += `<option value="${v.cityid}">${v.cityname}</option>`;
                });

                $("#cityname").html(htmlcity);
            });
        });


    });
</script>

14Sept2019SirTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


</body>
</html>